In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train=pd.read_csv("train_final.csv",index_col=False)
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
1,255,255,255,255,255,255,255,255,255,255,...,0,0,0,0,0,0,0,0,0,10
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10

In [3]:
labels=df_train["784"] #last column

In [4]:
df_train.drop(df_train.columns[[784]],axis=1,inplace=True)
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,255,255,255,255,255,255,255,255,255,255,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
np.random.seed(1212)
from keras.models import Model
from keras.layers import *
from keras import optimizers
from keras.layers import Input,Dense
from keras.models import Sequential
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils

In [6]:
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,255,255,255,255,255,255,255,255,255,255,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
labels=np.array(labels)

In [8]:
from keras.utils.np_utils import to_categorical
cat=to_categorical(labels,num_classes=17)

In [9]:
l=[]
for i in range(65254):
    l.append(np.array(df_train[i:i+1]).reshape(28,28,1))

In [10]:
np.random.seed(7)

In [11]:
model=Sequential()
model.add(Conv2D(30,(5,5),input_shape=(28,28,1),activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(15,(3,3),activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(136,activation="relu"))
model.add(Dense(49,activation="relu"))
model.add(Dense(14,activation="softmax"))

In [12]:
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [13]:
model.fit(np.array(l),cat,shuffle=True,epochs=10)

Epoch 1/10
2040/2040 [==============================] - 44s 17ms/step - loss: 1.4412 - accuracy: 0.6692
Epoch 2/10
2040/2040 [==============================] - 34s 17ms/step - loss: 0.2498 - accuracy: 0.9245
Epoch 3/10
2040/2040 [==============================] - 35s 17ms/step - loss: 0.1714 - accuracy: 0.9487
Epoch 4/10
2040/2040 [==============================] - 36s 17ms/step - loss: 0.1427 - accuracy: 0.9560
Epoch 5/10
2040/2040 [==============================] - 35s 17ms/step - loss: 0.1237 - accuracy: 0.9610
Epoch 6/10
2040/2040 [==============================] - 36s 18ms/step - loss: 0.1117 - accuracy: 0.9649
Epoch 7/10
2040/2040 [==============================] - 33s 16ms/step - loss: 0.0979 - accuracy: 0.9692
Epoch 8/10
2040/2040 [==============================] - 34s 17ms/step - loss: 0.0964 - accuracy: 0.9693
Epoch 9/10
2040/2040 [==============================] - 33s 16ms/step - loss: 0.0886 - accuracy: 0.9723
Epoch 10/10
2040/2040 [==============================] - 34s 16ms/step - loss: 0.0854 - accuracy: 0.9723

In [14]:
from keras.models import model_from_json

In [15]:
# serialize model to JSON
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")

Saved model to disk

In [16]:
# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")

Loaded model from disk

In [17]:
import cv2
import numpy as np
img = cv2.imread('C:/Users/aksha/OneDrive/Desktop/final_year_project/data/out7.jpg',cv2.IMREAD_GRAYSCALE)
#kernel = np.ones((3,3),np.uint8)
cv2.imshow("wo",img)
cv2.waitKey(0)
cv2.destroyAllWindows()
#erosion = cv2.erode(img,kernel,iterations = 3)
#dilation = cv2.dilate(img,kernel,iterations = 1)
#img=dilation
if img is not None:
    #images.append(img)
    img=~img
    ret,thresh=cv2.threshold(img,127,255,cv2.THRESH_BINARY)
    ctrs,ret=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    cnt=sorted(ctrs, key=lambda ctr: cv2.boundingRect(ctr)[0])
    w=int(28)
    h=int(28)
    train_data=[]
    #print(len(cnt))
    rects=[]
    for c in cnt :
        x,y,w,h= cv2.boundingRect(c)
        rect=[x,y,w,h]
        rects.append(rect)
    #print(rects)
    bool_rect=[]
    for r in rects:
        l=[]
        for rec in rects:
            flag=0
            if rec!=r:
                if r[0]<(rec[0]+rec[2]+10) and rec[0]<(r[0]+r[2]+10) and r[1]<(rec[1]+rec[3]+10) and rec[1]<(r[1]+r[3]+10):
                    flag=1
                l.append(flag)
            if rec==r:
                l.append(0)
        bool_rect.append(l)
    #print(bool_rect)
    dump_rect=[]
    for i in range(0,len(cnt)):
        for j in range(0,len(cnt)):
            if bool_rect[i][j]==1:
                area1=rects[i][2]*rects[i][3]
                area2=rects[j][2]*rects[j][3]
                if(area1==min(area1,area2)):
                    dump_rect.append(rects[i])
    #print(len(dump_rect)) 
    final_rect=[i for i in rects if i not in dump_rect]
    #print(final_rect)
    for r in final_rect:
        x=r[0]
        y=r[1]
        w=r[2]
        h=r[3]
        im_crop =thresh[y:y+h+10,x:x+w+10]
        

        im_resize = cv2.resize(im_crop,(28,28))
        cv2.imshow("work",im_resize)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

        im_resize=np.reshape(im_resize,(1,28,28))
        train_data.append(im_resize)

In [18]:
from sympy import solve
from sympy import sympify
from sympy.abc import x, y, z, a, b
from sympy.parsing.sympy_parser import parse_expr

In [19]:
s=""
for i in range(len(train_data)):
    train_data[i]=np.array(train_data[i])
    train_data[i]=train_data[i].reshape(1,28,28,1)
    result=loaded_model.predict_classes(train_data[i])
    if(result[0]==10):
        s=s+"-"
    if(result[0]==11):
        s=s+"+"
    if(result[0]==0):
        s=s+"0"
    if(result[0]==1):
        s=s+"1"
    if(result[0]==2):
        s=s+"2"
    if(result[0]==3):
        s=s+"3"
    if(result[0]==4):
        s=s+"4"
    if(result[0]==5):
        s=s+"5"
    if(result[0]==6):
        s=s+"6"
    if(result[0]==7):
        s=s+"7"
    if(result[0]==8):
        s=s+"8"
    if(result[0]==9):
        s=s+"9"
    if(result[0]==12):
        s=s+"*"
    if(result[0]==13):
        s=s+"y"
    if(result[0]==14):
        s=s+"("
    if(result[0]==15):
        s=s+")"
    if(result[0]==16):
        s=s+"x"
#print(s)
equation  = s.replace('x','*x')
if "x" in equation:
    try:
        solution = solve(equation)
        print(solution[0])
    except:
        print("invalid equation")
else:
    print(eval(equation))

C:\Users\aksha\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '

-4/5